pygments: true
permalink: /post/:title
markdown: redcarpet2
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 5
name: "Tyler Benziger's Blog"
description: Tyler rants about things
url: http://tybenz.com
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
