pygments: true
permalink: /post/:title
markdown: rdiscount
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
name: "Tyler Benziger's Blog"
description: Tyler rants about things
url: http://tybenz.com
